# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\College\Third year\First Term\DSP\Tasks\Task 1\Signal-Viewer\GUI\SignalViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Signal Viewer")
        MainWindow.setFixedSize(1379, 870)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(42, 42, 42);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Channel1Viewer = QtWidgets.QFrame(self.centralwidget)
        self.Channel1Viewer.setGeometry(QtCore.QRect(290, 100, 731, 281))
        self.Channel1Viewer.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.Channel1Viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel1Viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel1Viewer.setObjectName("Channel1Viewer")
        self.Channel1Editor = QtWidgets.QFrame(self.centralwidget)
        self.Channel1Editor.setGeometry(QtCore.QRect(1090, 100, 261, 281))
        self.Channel1Editor.setStyleSheet("\n"
"background-color: rgb(24, 24, 24);")
        self.Channel1Editor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel1Editor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel1Editor.setObjectName("Channel1Editor")
        self.InnerWindowChannel1 = QtWidgets.QFrame(self.Channel1Editor)
        self.InnerWindowChannel1.setGeometry(QtCore.QRect(10, 10, 241, 261))
        self.InnerWindowChannel1.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);")
        self.InnerWindowChannel1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InnerWindowChannel1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InnerWindowChannel1.setObjectName("InnerWindowChannel1")
        self.zoomOutChannel1 = QtWidgets.QPushButton(self.InnerWindowChannel1)
        self.zoomOutChannel1.setGeometry(QtCore.QRect(140, 80, 41, 41))
        self.zoomOutChannel1.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 20px;\n"
"font-weight:800;")
        self.zoomOutChannel1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/zoom-out (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutChannel1.setIcon(icon)
        self.zoomOutChannel1.setIconSize(QtCore.QSize(24, 24))
        self.zoomOutChannel1.setObjectName("zoomOutChannel1")
        self.RewindChannel1 = QtWidgets.QPushButton(self.InnerWindowChannel1)
        self.RewindChannel1.setGeometry(QtCore.QRect(50, 140, 141, 31))
        self.RewindChannel1.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 15px;\n"
"font-weight:800;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/rewind-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RewindChannel1.setIcon(icon1)
        self.RewindChannel1.setObjectName("RewindChannel1")
        self.zoomInChannel1 = QtWidgets.QPushButton(self.InnerWindowChannel1)
        self.zoomInChannel1.setGeometry(QtCore.QRect(60, 80, 41, 41))
        self.zoomInChannel1.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 20px;\n"
"font-weight:800;")
        self.zoomInChannel1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/zoom-in (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInChannel1.setIcon(icon2)
        self.zoomInChannel1.setIconSize(QtCore.QSize(24, 24))
        self.zoomInChannel1.setObjectName("zoomInChannel1")
        self.Channel1Label = QtWidgets.QLabel(self.InnerWindowChannel1)
        self.Channel1Label.setGeometry(QtCore.QRect(80, 10, 91, 31))
        self.Channel1Label.setStyleSheet("color:white;\n"
"font-size: 18px")
        self.Channel1Label.setObjectName("Channel1Label")
        self.rabbitChannel2 = QtWidgets.QLabel(self.InnerWindowChannel1)
        self.rabbitChannel2.setGeometry(QtCore.QRect(200, 180, 31, 41))
        self.rabbitChannel2.setText("")
        self.rabbitChannel2.setPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/rabbit (2).png"))
        self.rabbitChannel2.setObjectName("rabbitChannel2")
        self.SpeedSliderChannel1 = QtWidgets.QSlider(self.InnerWindowChannel1)
        self.SpeedSliderChannel1.setGeometry(QtCore.QRect(60, 200, 131, 16))
        self.SpeedSliderChannel1.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: white;  \n"
"    border-radius: 6px;    \n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: rgb(0, 170, 255);\n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 6px;    \n"
"    margin: -4px 0;       \n"
"}\n"
"")
        self.SpeedSliderChannel1.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSliderChannel1.setObjectName("SpeedSliderChannel1")
        self.turtleChannel1 = QtWidgets.QLabel(self.InnerWindowChannel1)
        self.turtleChannel1.setGeometry(QtCore.QRect(20, 180, 31, 51))
        self.turtleChannel1.setText("")
        self.turtleChannel1.setPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/turtle (2).png"))
        self.turtleChannel1.setObjectName("turtleChannel1")
        self.Channel2Viewer = QtWidgets.QFrame(self.centralwidget)
        self.Channel2Viewer.setGeometry(QtCore.QRect(290, 500, 731, 281))
        self.Channel2Viewer.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.Channel2Viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel2Viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel2Viewer.setObjectName("Channel2Viewer")
        self.ScrollableBarForSignals = QtWidgets.QFrame(self.centralwidget)
        self.ScrollableBarForSignals.setGeometry(QtCore.QRect(0, 60, 251, 791))
        self.ScrollableBarForSignals.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ScrollableBarForSignals.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ScrollableBarForSignals.setObjectName("ScrollableBarForSignals")
        self.SignalEditingWindow = QtWidgets.QFrame(self.ScrollableBarForSignals)
        self.SignalEditingWindow.setGeometry(QtCore.QRect(10, 40, 231, 251))
        self.SignalEditingWindow.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.SignalEditingWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SignalEditingWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SignalEditingWindow.setObjectName("SignalEditingWindow")
        self.InnerSignalWindow = QtWidgets.QFrame(self.SignalEditingWindow)
        self.InnerSignalWindow.setGeometry(QtCore.QRect(10, 10, 211, 231))
        self.InnerSignalWindow.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);")
        self.InnerSignalWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InnerSignalWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InnerSignalWindow.setObjectName("InnerSignalWindow")
        self.Signal1Label = QtWidgets.QLabel(self.InnerSignalWindow)
        self.Signal1Label.setGeometry(QtCore.QRect(60, 10, 91, 31))
        self.Signal1Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 18px")
        self.Signal1Label.setObjectName("Signal1Label")
        self.RenameButton = QtWidgets.QPushButton(self.InnerSignalWindow)
        self.RenameButton.setGeometry(QtCore.QRect(30, 70, 131, 31))
        self.RenameButton.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 15px;\n"
"font-weight:800;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RenameButton.setIcon(icon3)
        self.RenameButton.setObjectName("RenameButton")
        self.ColorButton = QtWidgets.QPushButton(self.InnerSignalWindow)
        self.ColorButton.setGeometry(QtCore.QRect(30, 120, 131, 31))
        self.ColorButton.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 15px;\n"
"font-weight:800;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/color-wheel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ColorButton.setIcon(icon4)
        self.ColorButton.setObjectName("ColorButton")
        self.channel1Chaeckbox = QtWidgets.QCheckBox(self.InnerSignalWindow)
        self.channel1Chaeckbox.setGeometry(QtCore.QRect(20, 170, 81, 20))
        self.channel1Chaeckbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.channel1Chaeckbox.setObjectName("channel1Chaeckbox")
        self.channel2Checkbox = QtWidgets.QCheckBox(self.InnerSignalWindow)
        self.channel2Checkbox.setGeometry(QtCore.QRect(110, 170, 81, 20))
        self.channel2Checkbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.channel2Checkbox.setObjectName("channel2Checkbox")
        self.TaskBar = QtWidgets.QFrame(self.centralwidget)
        self.TaskBar.setGeometry(QtCore.QRect(-1, 0, 1381, 51))
        self.TaskBar.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.TaskBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TaskBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TaskBar.setObjectName("TaskBar")
        self.UploadButton = QtWidgets.QPushButton(self.TaskBar)
        self.UploadButton.setGeometry(QtCore.QRect(460, 10, 121, 28))
        self.UploadButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:transparent;\n"
"font-weight:800;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/downloads.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadButton.setIcon(icon5)
        self.UploadButton.setIconSize(QtCore.QSize(20, 20))
        self.UploadButton.setObjectName("UploadButton")
        self.ConnectToWebsite = QtWidgets.QPushButton(self.TaskBar)
        self.ConnectToWebsite.setGeometry(QtCore.QRect(630, 10, 171, 28))
        self.ConnectToWebsite.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:transparent;\n"
"font-weight:800;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/world-wide-web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ConnectToWebsite.setIcon(icon6)
        self.ConnectToWebsite.setIconSize(QtCore.QSize(20, 20))
        self.ConnectToWebsite.setObjectName("ConnectToWebsite")
        self.ExportButton = QtWidgets.QPushButton(self.TaskBar)
        self.ExportButton.setGeometry(QtCore.QRect(850, 10, 141, 31))
        self.ExportButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:transparent;\n"
"font-weight:800;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/share (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExportButton.setIcon(icon7)
        self.ExportButton.setIconSize(QtCore.QSize(20, 20))
        self.ExportButton.setObjectName("ExportButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 450, 1061, 20))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(300, 400, 31, 31))
        self.pushButton_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:rgb(24,24,24);\n"
"font-weight:800;\n"
"border-radius: 15px;")
        self.pushButton_13.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon8)
        self.pushButton_13.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(340, 400, 31, 31))
        self.pushButton_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:rgb(24,24,24);\n"
"font-weight:800;\n"
"border-radius: 15px;")
        self.pushButton_14.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/video-pause-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon9)
        self.pushButton_14.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(390, 410, 611, 16))
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: white;  \n"
"    border-radius: 3px;    \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #000000;  \n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 6px;    \n"
"    margin: -4px 0;       \n"
"}\n"
"")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(1050, 110, 16, 261))
        self.verticalSlider.setStyleSheet("QSlider::groove:vertical {\n"
"    width: 6px;\n"
"    background: white;  \n"
"    border-radius: 3px;   \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #000000;   \n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;    \n"
"    margin: 0 -4px;       \n"
"}\n"
"")
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(940, 60, 131, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 15px;\n"
"font-weight:800;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon10)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(1050, 510, 16, 261))
        self.verticalSlider_2.setStyleSheet("QSlider::groove:vertical {\n"
"    width: 6px;\n"
"    background: white;  \n"
"    border-radius: 3px;   \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #000000;   \n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 5px;    \n"
"    margin: 0 -4px;       \n"
"}\n"
"")
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(390, 810, 611, 16))
        self.horizontalSlider_3.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: white;  \n"
"    border-radius: 3px;    \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #000000;  \n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 6px;    \n"
"    margin: -4px 0;       \n"
"}\n"
"")
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(340, 800, 31, 31))
        self.pushButton_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:rgb(24,24,24);\n"
"font-weight:800;\n"
"border-radius: 15px;")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon9)
        self.pushButton_15.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(300, 800, 31, 31))
        self.pushButton_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"background-color:rgb(24,24,24);\n"
"font-weight:800;\n"
"border-radius: 15px;")
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon8)
        self.pushButton_16.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_16.setObjectName("pushButton_16")
        self.Channel2Editor = QtWidgets.QFrame(self.centralwidget)
        self.Channel2Editor.setGeometry(QtCore.QRect(1090, 500, 261, 281))
        self.Channel2Editor.setStyleSheet("\n"
"background-color: rgb(24, 24, 24);")
        self.Channel2Editor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel2Editor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel2Editor.setObjectName("Channel2Editor")
        self.InnerWindowChannel2 = QtWidgets.QFrame(self.Channel2Editor)
        self.InnerWindowChannel2.setGeometry(QtCore.QRect(10, 10, 241, 261))
        self.InnerWindowChannel2.setStyleSheet("\n"
"border-radius: 20px;\n"
"background-color: rgb(42, 42, 42);")
        self.InnerWindowChannel2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InnerWindowChannel2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InnerWindowChannel2.setObjectName("InnerWindowChannel2")
        self.ZoomOutChannel2 = QtWidgets.QPushButton(self.InnerWindowChannel2)
        self.ZoomOutChannel2.setGeometry(QtCore.QRect(140, 80, 41, 41))
        self.ZoomOutChannel2.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 20px;\n"
"font-weight:800;")
        self.ZoomOutChannel2.setText("")
        self.ZoomOutChannel2.setIcon(icon)
        self.ZoomOutChannel2.setIconSize(QtCore.QSize(24, 24))
        self.ZoomOutChannel2.setObjectName("ZoomOutChannel2")
        self.RewindButtonChannel2 = QtWidgets.QPushButton(self.InnerWindowChannel2)
        self.RewindButtonChannel2.setGeometry(QtCore.QRect(50, 140, 141, 31))
        self.RewindButtonChannel2.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 15px;\n"
"font-weight:800;")
        self.RewindButtonChannel2.setIcon(icon1)
        self.RewindButtonChannel2.setObjectName("RewindButtonChannel2")
        self.zoomInChannel2 = QtWidgets.QPushButton(self.InnerWindowChannel2)
        self.zoomInChannel2.setGeometry(QtCore.QRect(60, 80, 41, 41))
        self.zoomInChannel2.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px;\n"
"border-radius: 20px;\n"
"font-weight:800;")
        self.zoomInChannel2.setText("")
        self.zoomInChannel2.setIcon(icon2)
        self.zoomInChannel2.setIconSize(QtCore.QSize(24, 24))
        self.zoomInChannel2.setObjectName("zoomInChannel2")
        self.Channel2Label = QtWidgets.QLabel(self.InnerWindowChannel2)
        self.Channel2Label.setGeometry(QtCore.QRect(80, 10, 91, 31))
        self.Channel2Label.setStyleSheet("color: white;\n"
"font-size: 18px")
        self.Channel2Label.setObjectName("Channel2Label")
        self.RabbitChannel2 = QtWidgets.QLabel(self.InnerWindowChannel2)
        self.RabbitChannel2.setGeometry(QtCore.QRect(200, 180, 31, 41))
        self.RabbitChannel2.setText("")
        self.RabbitChannel2.setPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/rabbit (2).png"))
        self.RabbitChannel2.setObjectName("RabbitChannel2")
        self.SpeedSliderChannel2 = QtWidgets.QSlider(self.InnerWindowChannel2)
        self.SpeedSliderChannel2.setGeometry(QtCore.QRect(60, 200, 131, 16))
        self.SpeedSliderChannel2.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: white;  \n"
"    border-radius: 6px;    \n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: rgb(0, 170, 255);\n"
"    border: 1px solid #333333;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 6px;    \n"
"    margin: -4px 0;       \n"
"}\n"
"")
        self.SpeedSliderChannel2.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSliderChannel2.setObjectName("SpeedSliderChannel2")
        self.TurtleChannel2 = QtWidgets.QLabel(self.InnerWindowChannel2)
        self.TurtleChannel2.setGeometry(QtCore.QRect(20, 180, 31, 51))
        self.TurtleChannel2.setText("")
        self.TurtleChannel2.setPixmap(QtGui.QPixmap("D:\\College\\Third year\\First Term\\DSP\\Tasks\\Task 1\\Signal-Viewer\\GUI\\Deliverables/turtle (2).png"))
        self.TurtleChannel2.setObjectName("TurtleChannel2")
        self.ScrollableBarForSignals.raise_()
        self.Channel1Viewer.raise_()
        self.Channel1Editor.raise_()
        self.Channel2Viewer.raise_()
        self.TaskBar.raise_()
        self.line.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.horizontalSlider_2.raise_()
        self.verticalSlider.raise_()
        self.pushButton_7.raise_()
        self.verticalSlider_2.raise_()
        self.horizontalSlider_3.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.Channel2Editor.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RewindChannel1.setText(_translate("MainWindow", " Rewind"))
        self.Channel1Label.setText(_translate("MainWindow", "Channel 1"))
        self.Signal1Label.setText(_translate("MainWindow", "Signal#1"))
        self.RenameButton.setText(_translate("MainWindow", "Rename"))
        self.ColorButton.setText(_translate("MainWindow", "Change Color"))
        self.channel1Chaeckbox.setText(_translate("MainWindow", "Channel 1"))
        self.channel2Checkbox.setText(_translate("MainWindow", "Channel 2"))
        self.UploadButton.setText(_translate("MainWindow", "Upload File"))
        self.ConnectToWebsite.setText(_translate("MainWindow", "Connect to website"))
        self.ExportButton.setText(_translate("MainWindow", "Export to PDF"))
        self.pushButton_7.setText(_translate("MainWindow", " Link channels"))
        self.RewindButtonChannel2.setText(_translate("MainWindow", " Rewind"))
        self.Channel2Label.setText(_translate("MainWindow", "Channel 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
